### ISSUE TITLE
前端和后端工程合并，支持一体化打包运行

### ISSUE THREAD

**Issue by johnlanni** [higress-group/higress-console#10]
- [ ] 将前端build产物放进后端resource目录
- [ ] 调整后端路由和api路径配置

**Comment by CH3CHO** [comment]
申请认领本任务

**Comment by CH3CHO** [comment]
backend项目里用了Maven Wrapper，但是不是少提交了一个文件呢？

`backend\.mvn\wrapper\maven-wrapper.properties`

**Comment by CH3CHO** [comment]
> 

这个问题我做这个任务的时候一并修正吧。
