### ISSUE TITLE
监控面板会在某些操作下导致展示异常

### ISSUE THREAD

**Issue by 912988434** [higress-group/higress-console#152]
在对监控面板内嵌的grafana进行某些操作后会导致页面出现异常
异常如下：
<img width="1791" alt="image" src="https://user-images.githubusercontent.com/35693221/226506288-1c132bb7-776a-4c69-8652-d5a597be49dc.png">
复现步骤
1、在内嵌的grafana中点击sign in
<img width="1736" alt="image" src="https://user-images.githubusercontent.com/35693221/226506495-ec2a53de-8e45-4518-80f3-fd2fc02d18be.png">
2、在新出现的404页面点击返回
<img width="1541" alt="image" src="https://user-images.githubusercontent.com/35693221/226506843-5829e759-1ee4-47ed-9a4a-91be20ede76d.png">
3、然后就呈现出画中画效果
<img width="1791" alt="image" src="https://user-images.githubusercontent.com/35693221/226506933-222617bb-5a3e-4b66-abd8-34f84aac2362.png">

**Comment by CH3CHO** [comment]
这个是 Grafana 登录跳转的路径不正确所致。后面我们看看如何处理。
