### ISSUE TITLE
Plugin overview does not respect language

### ISSUE THREAD

**Issue by tomkerkhove** [higress-group/higress-console#202]
- [x] I have searched the [issues](https://github.com/alibaba/higress/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

Plugin overview does not respect language:
![image](https://user-images.githubusercontent.com/4345663/231458660-f342421f-fe92-4ccb-8a53-df3b214979c6.png)

### Ⅱ. Describe what happened

Plug-ins are listed in Chinese.

### Ⅲ. Describe what you expected to happen

Plug-ins should be listed in English.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. Switch to English
2. Go to plugins page

### Ⅴ. Anything else we need to know?
N/A

### Ⅵ. Environment:

- Higress Console version:  0.2.0
- OS :
- Others:

**Comment by CH3CHO** [comment]
I18n of plugin management is still under development. Any new progress will be updated in this issue. Thanks.
