### ISSUE TITLE
路由配置中支持注解配置功能

### ISSUE THREAD

**Issue by cf1998** [higress-group/higress-console#271]
## Why do you need it?
能够通过Higress控制台对Higress进行配置注解来实现更多功能，比如灰度发布，gRPC协议支持等！

## How could it be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by CH3CHO** [comment]
如果用户在注解配置的地方配置了 Console 已经支持了的功能，导致两边的配置出现冲突，Console 应该以那边的配置为准呢？

举个例子：

路径匹配时是否忽略大小写是通过 `higress.io/ignore-path-case` 这个注解实现的。如果用户在界面上没有勾选“忽略大小写”，但在注解配置区配置了 `higress.io/ignore-path-case: "false"`，Console 的行为应为以下哪种呢：
1. 以界面选择为准，即不忽略大小写
2. 以注解配置为准，即忽略大小写
3. 报错，告知用户不可以在注解配置中添加界面上已经支持了的配置

@johnlanni，@cf1998，二位怎么看？

**Comment by johnlanni** [comment]
@CH3CHO 我觉得第三个方式比较合理
