### ISSUE TITLE
是否可以更新springboot版本

### ISSUE THREAD

**Issue by kvsl0** [higress-group/higress-console#305]
## Why do you need it?
 Is your feature request related to a problem? Please describe in details
higress-console目前基于springboot2.5.4版本，导致阿里云检测到漏洞

## How could it be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.
可以基于jdk lts版更新到springboot 3或springboot 2.7版本

## Other related information
![image](https://github.com/higress-group/higress-console/assets/57879161/ca45090f-d207-4e3c-bebd-5466257a891a)

**Comment by CH3CHO** [comment]
可以的。
