### ISSUE TITLE
请问下将前端后端镜像打包到一起使用backend中的Dockerfile就可以吗?

### ISSUE THREAD

**Issue by ilovedumplings** [higress-group/higress-console#368]
## Why do you need it?
 Is your feature request related to a problem? Please describe in details

## How could it be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

**Comment by CH3CHO** [comment]
你直接用 backend 里的构建脚本去构建就行了，会自动把前端打进去。

**Comment by ilovedumplings** [comment]
> 你直接用 backend 里的构建脚本去构建就行了，会自动把前端打进去。

好嘞哥

**Comment by ilovedumplings** [comment]
> 你直接用 backend 里的构建脚本去构建就行了，会自动把前端打进去。

请问下maven-gpg-plugin.version 这个插件的作用是什么啊?我编译的时候找不到gpg  Could not determine gpg version ,我需要安装一个嘛?

**Comment by CH3CHO** [comment]
看一下 backend 下面的 build.sh

**Comment by CH3CHO** [comment]
@ilovedumplings 请问还有问题吗？

**Comment by ilovedumplings** [comment]
> @ilovedumplings 请问还有问题吗？

没有问题了老哥,我给关了,感恩
