### ISSUE TITLE
higress-console自定义插件状态无法跟实际规则匹配

### ISSUE THREAD

**Issue by lswzw** [higress-group/higress-console#375]
一问题描述
使用console查看配置的wasm插件状态一直是关闭，但实际用命令查看状态为开启。

二描述发生了什么
![wechat_2024-12-03_103723_594](https://github.com/user-attachments/assets/97caf4e2-0719-437f-a576-62f4efd327f6)

三描述你期望发生的事情
希望console查看到的状态能跟命令查询的状态保持一致。

四如何复现它（尽可能少和精确）
1.在console里面添加一个自定义插件。状态为开启。
2.在命令里面查看状态，通过命令修改配置保存。
3.回到console查看状态为关闭。但用命令查看为开启。

六环境：
-Higress版本：2.0.3
- Console ： 1.4.5
-操作系统：k8s-1.19.X

**Comment by johnlanni** [comment]
higress-console 1.4.6 修复了这个问题，可以先修改一下 console 的镜像。后面会发布一个 higress 的新版本。
