### ISSUE TITLE
自定义插件启用后 UI显示异常

### ISSUE THREAD

**Issue by KingOfXi** [higress-group/higress-console#377]
- [ ] I have searched the [issues](https://github.com/alibaba/higress/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
自定义插件开启然后点击保存
![企业微信截图_17338863728054](https://github.com/user-attachments/assets/f2141f3c-b51b-4b4f-a3df-b15d7de0d515)
然后点击其他位置，比如路由配置，再点击策略，点击自定义插件，可以看到 UI的开启状态是 不开启，但是实际接口返回的enable：true，实际验证接口该策略也是开启的，所以判断是UI的显示问题
![企业微信截图_1733886418804](https://github.com/user-attachments/assets/7003afe7-83a2-4dc4-8c84-b60b44c0395d)

### Ⅵ. Environment:

- Higress console:  1.4.6

**Comment by CH3CHO** [comment]
问题已经重现。后续会进行修复。
