### ISSUE TITLE
grafana导入dashboard无法展示数据-使用vm数据库

### ISSUE THREAD

**Issue by vvhuang-ll** [higress-group/higress-console#386]
- [x] I have searched the [issues](https://github.com/alibaba/higress/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
grafana导入dashboard无法展示数据，监控数据存储在vm数据库。导入json修改数据源后无法获取到数据
label_values(envoy_server_live, higress) 没有higress这个labels
![image](https://github.com/user-attachments/assets/c6ce400d-1804-404c-ba31-665397373dc3)

**Comment by vvhuang-ll** [comment]
gwteway 暴露的指标是不包含higress这个label的，higress 这个label 是prometheus写死的吗

**Comment by CH3CHO** [comment]
> gwteway 暴露的指标是不包含higress这个label的，higress 这个label 是prometheus写死的吗

这个是从 pod label 上转过去的

**Comment by vvhuang-ll** [comment]
我明白了
