### ISSUE TITLE
请问插件中的configSchema和routeConfigSchema的区别是什么?

### ISSUE THREAD

**Issue by ilovedumplings** [higress-group/higress-console#387]
在console代码里只搜到了configSchema的解析 没有搜到 routeConfigSchema的解析代码
![Uploading image.png…]()

**Comment by CH3CHO** [comment]
routeConfigSchema是非标配法，后续会改掉

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月19日 15:46 |
| 收件人 | ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [higress-group/higress-console] 请问插件中的configSchema和routeConfigSchema的区别是什么? (Issue #387) |

在console代码里只搜到了configSchema的解析 没有搜到 routeConfigSchema的解析代码

**Comment by ilovedumplings** [comment]
> routeConfigSchema是非标配法，后续会改掉
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年12月19日 15:46 | | 收件人 | ***@***.***> | | 抄送人 | Subscribed ***@***.***> | | 主题 | [higress-group/higress-console] 请问插件中的configSchema和routeConfigSchema的区别是什么? (Issue #387) | 在console代码里只搜到了configSchema的解析 没有搜到 routeConfigSchema的解析代码 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

大哥!快! 晓得了!
