### ISSUE TITLE
完善后端项目代码格式检查

### ISSUE THREAD

**Issue by johnlanni** [higress-group/higress-console#52]
可以参考 seata 的配置
seata config: https://github.com/seata/seata/blob/0112719ad0e8c4225a9f59a8598f83cda296a760/pom.xml#L268
seata checkstyle.xml: https://github.com/seata/seata/blob/2.x/style/seata_checkstyle.xml
seata suppressions.xml: https://github.com/seata/seata/blob/2.x/style/seata_suppressions.xml

**Comment by CH3CHO** [comment]
认领此任务
