### ISSUE TITLE
路由`基础策略`配置的前端绘制

### ISSUE THREAD

**Issue by johnlanni** [higress-group/higress-console#57]
## 入口：
![image](https://user-images.githubusercontent.com/6763318/216906427-a5bb60c3-1889-4d88-97e0-5f6b3a094d0b.png)

## 预期效果：
卡片方式呈现
![image](https://user-images.githubusercontent.com/6763318/216906749-ac409339-fe04-4d4c-8c22-e330d4358d04.png)

### 重写：
![image](https://user-images.githubusercontent.com/6763318/216905817-812d2ead-1b20-4e8f-b144-e726be068aef.png)

### Header设置：
![image](https://user-images.githubusercontent.com/6763318/216905875-b54ab939-66fb-4a38-966d-3c5ea1f7f576.png)

### 跨域：
![image](https://user-images.githubusercontent.com/6763318/216906010-f955a46b-a8f8-4be2-b2d0-6284388bcd44.png)

### 重试：
![image](https://user-images.githubusercontent.com/6763318/216906314-42fad4fb-ef5a-46bd-92ee-f96c556285de.png)

**Comment by songpengyuan** [comment]
申请认领任务
