### ISSUE TITLE
路由`基础策略`中的跨域策略实现

### ISSUE THREAD

**Issue by johnlanni** [higress-group/higress-console#61]
根据 #58 定义的API实现到 Ingress annotation 的对应转换

注解 | 说明
-- | --
higress.io/enable-cors | 开启或关闭跨域。
higress.io/cors-allow-origin | 允许的第三方站点，第三方站点之间使用英文逗号分隔，支持通配符*。默认值为*，即允许所有第三方站点。
higress.io/cors-allow-methods | 允许的请求方法，如GET、POST、PUT等，请求方法之间使用英文逗号分隔，支持通配符*。默认值为GET、PUT、POST、DELETE、PATCH、OPTIONS。
higress.io/cors-allow-headers | 允许的请求Header，Header之间使用英文逗号分隔，支持通配符*。默认值为DNT、X-CustomHeader、Keep-Alive、User-Agent、X-Requested-With、If-Modified-Since、Cache-Control、Content-Type、Authorization。
higress.io/cors-expose-headers | 允许暴露给浏览器的响应Header，响应Header之间使用英文逗号分隔。
higress.io/cors-allow-credentials | 是否允许携带凭证信息。默认允许。
higress.io/cors-max-age | 预检结果的最大缓存时间，单位为秒。默认值为1728000秒。

**Comment by jameszhangyukun** [comment]
申请认领任务
