### ISSUE TITLE
优化前端构建流程，解决静态资源缓存问题

### ISSUE THREAD

**Issue by CH3CHO** [higress-group/higress-console#84]
目前每次重新发布后，都会出现由于静态资源被缓存而导致的界面功能异常问题。被缓存的资源有两部分：

1. 构建生成的静态资源
2. 国际化资源、图片等原始静态资源

故希望能够通过优化前端构建流程的方法，解决静态资源缓存问题。

**Comment by songpengyuan** [comment]
申请认领任务
