### ISSUE TITLE
提升 KubernetesModelConverter 的单测覆盖率

### ISSUE THREAD

**Issue by CH3CHO** [higress-group/higress-console#97]
KubernetesModelConverter 是负责将数据在业务模型与 K8s CRD 之间进行转换的核心模块。单元测试需要尽可能的覆盖其各个功能分支。

**Comment by jameszhangyukun** [comment]
申请认领任务

**Comment by psxjoy** [comment]
Is anyone still working on this issue?
If not, I’d be happy to take it over and move it forward. Please feel free to assign it to me. @CH3CHO

**Comment by CH3CHO** [comment]
Thanks. You can do it. I will assign it to you later.

| |
Kent Dong
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月19日 14:23 |
| 收件人 | higress-group/higress-console ***@***.***> |
| 抄送人 | Kent ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [higress-group/higress-console] 提升 KubernetesModelConverter 的单测覆盖率 (Issue #97) |

Is anyone still working on this issue?
If not, I’d be happy to take it over and move it forward. Please feel free to assign it to me. @CH3CHO
